pub type Bytes = [u8];
pub type TransportFrame = [u8];

// Following enums have been copied over from Koenkk's Zigbee-Herdsman
// https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/unpi/constants.ts
pub enum Type {
	POLL = 0,
	SREQ = 1,
	AREQ = 2,
	SRSP = 3,
	Reserved = 4,
}


#[derive()]
pub enum ZnpCommandStatus {
	Success = 0x00,
	Failure = 0x01,
	InvalidParam = 0x02,
	NvItemInitialized = 0x09,
	NvOperFailed = 0x0a,
	NvBadItemLen = 0x0c,
	MemError = 0x10,
	BufferFull = 0x11,
	UnsupportedMode = 0x12,
	MacMemError = 0x13,
	MacUnsupportedNotSpoort = 0x18,
	MacBadState = 0x19,
	MacNoResources = 0x1a,
	MacAckPending = 0x1b,
	MacNoTime = 0x1c,
	MacTxAborted = 0x1d,
	SapiInProgress = 0x20,
	SapiTimeout = 0x21,
	SapiInit = 0x22,
	NotAuthorized = 0x7e,
	MalformedCmd = 0x80,
	UnsupClusterCmd = 0x81,
	OtaAbort = 0x95,
	OtaImageInvalid = 0x96,
	OtaWaitForData = 0x97,
	OtaNoImageAvailable = 0x98,
	OtaRequireMoreImage = 0x99,
	ApsFail = 0xb1,
	ApsTableFull = 0xb2,
	ApsIllegalRequest = 0xb3,
	ApsInvalidBinding = 0xb4,
	ApsUnsupportedAttrib = 0xb5,
	ApsNotSupported = 0xb6,
	ApsNoAck = 0xb7,
	ApsDuplicateEntry = 0xb8,
	ApsNoBoundDevice = 0xb9,
	ApsNotAllowed = 0xba,
	ApsNotAuthenticated = 0xbb,
	SecNoKey = 0xa1,
	SecOldFrmCount = 0xa2,
	SecMaxFrmCount = 0xa3,
	SecCcmFail = 0xa4,
	NwkInvalidParam = 0xc1,
	NwkInvalidRequest = 0xc2,
	NwkNotPermitted = 0xc3,
	NwkStartupFailure = 0xc4,
	NwkAlreadyPresent = 0xc5,
	NwkSyncFailure = 0xc6,
	NwkTableFull = 0xc7,
	NwkUnknownDevice = 0xc8,
	NwkUnsupportedAttribute = 0xc9,
	NwkNoNetworks = 0xca,
	NwkLeaveUnconfirmed = 0xcb,
	NwkNoAck = 0xcc,
	NwkNoRoute = 0xcd,
	MacBeaconLoss = 0xe0,
	MacChannelAccessFailure = 0xe1,
	MacDenied = 0xe2,
	MacDisableTrxFailure = 0xe3,
	MacFailedSecurityCheck = 0xe4,
	MacFrameTooLong = 0xe5,
	MacInvalidGts = 0xe6,
	MacInvalidHandle = 0xe7,
	MacInvalidParameter = 0xe8,
	MacNoAck = 0xe9,
	MacNoBeacon = 0xea,
	MacNoData = 0xeb,
	MacNoShortAddr = 0xec,
	MacOutOfCap = 0xed,
	MacPanidConflict = 0xee,
	MacRealignment = 0xef,
	MacTransactionExpired = 0xf0,
	MacTransactionOverflow = 0xf1,
	MacTxActive = 0xf2,
	MacUnavailableKey = 0xf3,
	MacUnsupportedAttribute = 0xf4,
	MacUnsupported = 0xf5,
	MacOnTimeTooLing = 0xf6,
	MacPastTime = 0xf7,
	MacTrackingOff = 0xf8,
	MacScanInProgress = 0xfc,
	MacSrcMatchInvalidIndex = 0xff,
}

